services:
  docs:
    image: supply_chain_local_docs
    container_name: supply_chain_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./supply_chain:/app/supply_chain:z
    ports:
      - '9000:9000'
    command: /start-docs
