# Generated by Django 5.0.10 on 2024-12-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("has_analysis", models.BooleanField(default=False)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "change",
                    models.IntegerField(
                        choices=[(-2, "-2"), (-1, "-1"), (0, "0"), (1, "1"), (2, "2")],
                        default=0,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="products", to="product.category"
                    ),
                ),
            ],
        ),
    ]
